export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SAVE_EDIT_NAME = 'SAVE_EDIT_NAME';
export const SAVE_EDIT_PHONE = 'SAVE_EDIT_PHONE';
export const SAVE_EDIT_ADDRESS = 'SAVE_EDIT_ADDRESS';
export const SAVE_EDIT_COMPANY = 'SAVE_EDIT_COMPANY';
export const SAVE_EDIT_EMAIL = 'SAVE_EDIT_EMAIL';

